### PR TITLE
Fix ruby version

### PR DESCRIPTION
**Pull request by oblute**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by oblute** [comment]
@conda-forge-admin, please rerender

**Comment by sodre** [comment]
@oblute, be careful with this change. the previous version was only failing for rb2.5 and osx. Consider restricting the change to only that environment combination.

**Comment by oblute** [comment]
@sodre the change to add use system libraries? how would i restrict it for just that? it seems to work on all of them

**Comment by sodre** [comment]
you can use the selectors, e.g. # [osx and rb25]

**Pull request merged**
